//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DALResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DALResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DAL.DALResources", typeof(DALResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuizDBConection.
        /// </summary>
        internal static string DefaultDBString {
            get {
                return ResourceManager.GetString("DefaultDBString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXECUTE [dbo].[P_DELETEQUESTION] 
        ///                    @QuizID=@qid, 
        ///                    @QuestionID=@qsid, 
        ///                    @ERROR=@er OUT, 
        ///                    @ERRORTEXT=@et OUT.
        /// </summary>
        internal static string P_DeleteQuestion {
            get {
                return ResourceManager.GetString("P_DeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXECUTE [dbo].[P_DELETEQUIZ] 
        ///                    @QuizID=@qid, 
        ///                    @ERROR=@er OUT, 
        ///                    @ERRORTEXT=@et OUT.
        /// </summary>
        internal static string P_DeleteQuiz {
            get {
                return ResourceManager.GetString("P_DeleteQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXECUTE [dbo].[P_DELETEUSER] @USERID = @id, @ERROR=@er OUT, @ERRORTEXT=@et OUT.
        /// </summary>
        internal static string P_DeleteUser {
            get {
                return ResourceManager.GetString("P_DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXECUTE [dbo].[P_DELETEVARIANT] 
        ///                @QuizID=@qid, 
        ///                @QuestionID=@qsid, 
        ///                @VariantID=@vid,
        ///                @ERROR=@er OUT, 
        ///                @ERRORTEXT=@et OUT.
        /// </summary>
        internal static string P_DeleteVariant {
            get {
                return ResourceManager.GetString("P_DeleteVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXECUTE [dbo].[P_GETALLQUIZES] @RecordsCount = @rc.
        /// </summary>
        internal static string P_GetAllQuizes {
            get {
                return ResourceManager.GetString("P_GetAllQuizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXECUTE [dbo].[P_GETALLUSERS] @RecordsCount = @rc.
        /// </summary>
        internal static string P_GetAllUsers {
            get {
                return ResourceManager.GetString("P_GetAllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXECUTE [dbo].[P_GETNEXTQUESTION] 
        ///                    @RecordCount=@rc,
        ///                    @QuizResultId=@qrid.
        /// </summary>
        internal static string P_GetNextQuestion {
            get {
                return ResourceManager.GetString("P_GetNextQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXECUTE [dbo].[P_GETQUIZASSIGNMENT] 
        ///                    @UserId=@uid.
        /// </summary>
        internal static string P_GetQuizAssignment {
            get {
                return ResourceManager.GetString("P_GetQuizAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXECUTE P_GETQUIZRESULT @QuizResultId = @qrid.
        /// </summary>
        internal static string P_GetQuizResult {
            get {
                return ResourceManager.GetString("P_GetQuizResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXECUTE [dbo].[P_GETQUIZRESULTS] @UserId = @uid.
        /// </summary>
        internal static string P_GetQuizResults {
            get {
                return ResourceManager.GetString("P_GetQuizResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXECUTE[dbo].[P_SAVEANSWER] 
        ///                                        @QuizResultID=@qrid,
        ///                                        @QuestionID=@qsid, 
        ///                                        @AnswerID = @Aid,
        ///                                        @AnswerFlag=@af,
        ///                                        @ERROR=@er OUT, 
        ///                                        @ERRORTEXT=@et OUT.
        /// </summary>
        internal static string P_SaveAnswer {
            get {
                return ResourceManager.GetString("P_SaveAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXECUTE [dbo].[P_SAVEQUESTION] 
        ///                                        @QuizID=@qid, 
        ///                                        @QuestionID=@qsid, 
        ///                                        @info = @i,
        ///                                        @text=@t,
        ///                                        @CorrectOptionFlag=@cof,
        ///                                        @ERROR=@er OUT, 
        ///                                        @ERRORTEXT=@et OUT.
        /// </summary>
        internal static string P_SaveQuestion {
            get {
                return ResourceManager.GetString("P_SaveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXECUTE [dbo].[P_SAVEQUIZ] 
        ///                    @QuizID=@qid, 
        ///                    @QuizName = @qn,
        ///                    @AuthorID = @a,
        ///                    @CreatedDate=@cdt,
        ///                    @SuccessRate=@sr,
        ///                    @ERROR=@er OUT, 
        ///                    @ERRORTEXT=@et OUT.
        /// </summary>
        internal static string P_SaveQuiz {
            get {
                return ResourceManager.GetString("P_SaveQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXECUTE [dbo].[P_SAVEQUIZASSIGNMENT] 
        ///                    @XmlQuizes=@xmlq,
        ///                    @ERROR=@er OUT, 
        ///                    @ERRORTEXT=@et OUT.
        /// </summary>
        internal static string P_SaveQuizAssignment {
            get {
                return ResourceManager.GetString("P_SaveQuizAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXECUTE [dbo].[P_SAVEQUIZRESULT] 
        ///                    @QuizResultId=@qrid, 
        ///                    @ERROR=@er OUT, 
        ///                    @ERRORTEXT=@et OUT.
        /// </summary>
        internal static string P_SaveQuizResult {
            get {
                return ResourceManager.GetString("P_SaveQuizResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXECUTE [dbo].[P_SAVEUSER] @USERID=@Uid, @USERNAME=@Unm, @FIRSTNAME=@fn, @LASTNAME=@ln, @HASHEDPASSWORD=@hp, @SALT=@st,  @ROLESFLAG=@rf, @LastLogonDate=@lld, @ERROR=@er OUT, @ERRORTEXT=@et OUT.
        /// </summary>
        internal static string P_SaveUser {
            get {
                return ResourceManager.GetString("P_SaveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXECUTE [dbo].[P_SAVEVARIANT] 
        ///                                        @QuizID=@qid, 
        ///                                        @QuestionID=@qsid, 
        ///                                        @VariantID = @vid,
        ///                                        @text=@t,
        ///                                        @ERROR=@er OUT, 
        ///                                        @ERRORTEXT=@et OUT.
        /// </summary>
        internal static string P_SaveVariant {
            get {
                return ResourceManager.GetString("P_SaveVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXECUTE [dbo].[P_SETLOGONDATE] @USERNAME = @uname.
        /// </summary>
        internal static string P_SetLogonDate {
            get {
                return ResourceManager.GetString("P_SetLogonDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXECUTE [dbo].[P_StatsAllQuizes].
        /// </summary>
        internal static string P_StatsAllQuizes {
            get {
                return ResourceManager.GetString("P_StatsAllQuizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXECUTE [dbo].[P_StatsAllUsers].
        /// </summary>
        internal static string P_StatsAllUsers {
            get {
                return ResourceManager.GetString("P_StatsAllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXECUTE [dbo].[P_StatsByQuiz] @Quiz_Id = @qid.
        /// </summary>
        internal static string P_StatsByQuiz {
            get {
                return ResourceManager.GetString("P_StatsByQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXECUTE [dbo].[P_StatsByUser] @User_Id = @uid.
        /// </summary>
        internal static string P_StatsByUser {
            get {
                return ResourceManager.GetString("P_StatsByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXECUTE [dbo].[P_StatsByUserQuiz] @User_Id = @uid, @Quiz_Id = @qid.
        /// </summary>
        internal static string P_StatsByUserQuiz {
            get {
                return ResourceManager.GetString("P_StatsByUserQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd HH:mm:ss.fff.
        /// </summary>
        internal static string S_DatetimeFormatString {
            get {
                return ResourceManager.GetString("S_DatetimeFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete is Ok.
        /// </summary>
        internal static string S_ISDeleteOk {
            get {
                return ResourceManager.GetString("S_ISDeleteOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already used! Choose another!.
        /// </summary>
        internal static string S_IsValidMessageAlreadyUsed {
            get {
                return ResourceManager.GetString("S_IsValidMessageAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person is Ok.
        /// </summary>
        internal static string S_IsValidMessageOk {
            get {
                return ResourceManager.GetString("S_IsValidMessageOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is empty, it is not allowed!.
        /// </summary>
        internal static string S_ValidatePassword_Empty {
            get {
                return ResourceManager.GetString("S_ValidatePassword_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is too short, minimal length is 2 symbols!.
        /// </summary>
        internal static string S_ValidatePassword_TooShort {
            get {
                return ResourceManager.GetString("S_ValidatePassword_TooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT USER_ID,FIRSTNAME,LASTNAME, USERNAME,HASHEDPASSWORD, SALT, ROLESFLAG, REGISTRATION_DATE,LAST_LOGON_DATE FROM QuizDB.dbo.V_M_USERS;.
        /// </summary>
        internal static string SQLLoadPersons {
            get {
                return ResourceManager.GetString("SQLLoadPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuizDBTestConnection.
        /// </summary>
        internal static string TestDBString {
            get {
                return ResourceManager.GetString("TestDBString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [QUESTION_ID]
        ///      ,[QUIZ_ID]
        ///      ,[INFO]
        ///      ,[TEXT]
        ///      ,[CORRECT_OPTION_FLAG]
        ///  FROM [dbo].[V_M_QUESTIONS]
        ///WHERE QUIZ_ID = @quiz_id.
        /// </summary>
        internal static string V_Get_QuestionsList {
            get {
                return ResourceManager.GetString("V_Get_QuestionsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXECUTE dbo.[P_GETQUIZ] @ID =@quiz_id.
        /// </summary>
        internal static string V_Get_Quiz {
            get {
                return ResourceManager.GetString("V_Get_Quiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT USER_ID,FIRSTNAME,LASTNAME, USERNAME,HASHEDPASSWORD, SALT, ROLESFLAG, 		CONVERT(nvarchar(23),[REGISTRATION_DATE],121) as [REGISTRATION_DATE] , 
        ///		CONVERT(nvarchar(23),[LAST_LOGON_DATE],121) as [LAST_LOGON_DATE]
        /// FROM dbo.V_M_USERS WHERE USER_ID = @user_id.
        /// </summary>
        internal static string V_Get_User {
            get {
                return ResourceManager.GetString("V_Get_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [ROLE_ID]
        ///      ,[ROLE_NAME]
        ///      ,[ROLE_FLAG]
        ///      ,[ALLOWED_METHODS]
        ///  FROM [dbo].[V_M_ROLES].
        /// </summary>
        internal static string V_GetAllRoles {
            get {
                return ResourceManager.GetString("V_GetAllRoles", resourceCulture);
            }
        }
    }
}
