CREATE TABLE [dbo].[S_PK_GENERATOR](
	[TABLE_NAME] [varchar](30) NOT NULL,
	[TABLE_ID] [numeric](18, 0) NOT NULL,

    CONSTRAINT [XPK_S_PK_GENERATOR] PRIMARY KEY CLUSTERED (	[TABLE_NAME] ASC)
) ON [PRIMARY]
