//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QuizResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QuizResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Quiz.Resources.QuizResources", typeof(QuizResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user can&apos;t be deleted, error :.
        /// </summary>
        public static string S_CantDeleteUser {
            get {
                return ResourceManager.GetString("S_CantDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error create question!.
        /// </summary>
        public static string S_ErrorCreateQuestion {
            get {
                return ResourceManager.GetString("S_ErrorCreateQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error create quiz!.
        /// </summary>
        public static string S_ErrorCreateQuiz {
            get {
                return ResourceManager.GetString("S_ErrorCreateQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error create variant !.
        /// </summary>
        public static string S_ErrorCreateVariants {
            get {
                return ResourceManager.GetString("S_ErrorCreateVariants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error delete question!.
        /// </summary>
        public static string S_ErrorDeleteQuestion {
            get {
                return ResourceManager.GetString("S_ErrorDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error delete quiz!.
        /// </summary>
        public static string S_ErrorDeleteQuiz {
            get {
                return ResourceManager.GetString("S_ErrorDeleteQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete user error!.
        /// </summary>
        public static string S_ErrorDeleteUser {
            get {
                return ResourceManager.GetString("S_ErrorDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error delete variant!.
        /// </summary>
        public static string S_ErrorDeleteVariant {
            get {
                return ResourceManager.GetString("S_ErrorDeleteVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error edit questions!.
        /// </summary>
        public static string S_ErrorEditQuestion {
            get {
                return ResourceManager.GetString("S_ErrorEditQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error edit variant!.
        /// </summary>
        public static string S_ErrorEditVariant {
            get {
                return ResourceManager.GetString("S_ErrorEditVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error get next question !.
        /// </summary>
        public static string S_ErrorGetNextQuiestion {
            get {
                return ResourceManager.GetString("S_ErrorGetNextQuiestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error get quiz list !.
        /// </summary>
        public static string S_ErrorGetQuizList {
            get {
                return ResourceManager.GetString("S_ErrorGetQuizList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error get user details!.
        /// </summary>
        public static string S_ErrorGetUserDetails {
            get {
                return ResourceManager.GetString("S_ErrorGetUserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error get user list!.
        /// </summary>
        public static string S_ErrorGetUserList {
            get {
                return ResourceManager.GetString("S_ErrorGetUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error get variants !.
        /// </summary>
        public static string S_ErrorGetVariants {
            get {
                return ResourceManager.GetString("S_ErrorGetVariants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error load MyQuizes data !.
        /// </summary>
        public static string S_ErrorLoadMyQuizes {
            get {
                return ResourceManager.GetString("S_ErrorLoadMyQuizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error open allquizes statistic page !.
        /// </summary>
        public static string S_ErrorOpenAllQuizes {
            get {
                return ResourceManager.GetString("S_ErrorOpenAllQuizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error open allusers statistic page !.
        /// </summary>
        public static string S_ErrorOpenAllUsers {
            get {
                return ResourceManager.GetString("S_ErrorOpenAllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error open quiz statistic page !.
        /// </summary>
        public static string S_ErrorOpenQuiz {
            get {
                return ResourceManager.GetString("S_ErrorOpenQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error open statistic page!.
        /// </summary>
        public static string S_ErrorOpenStatistic {
            get {
                return ResourceManager.GetString("S_ErrorOpenStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error open user statistic page !.
        /// </summary>
        public static string S_ErrorOpenUser {
            get {
                return ResourceManager.GetString("S_ErrorOpenUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error save answer!.
        /// </summary>
        public static string S_ErrorSaveAnswer {
            get {
                return ResourceManager.GetString("S_ErrorSaveAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error save question!.
        /// </summary>
        public static string S_ErrorSaveQuestion {
            get {
                return ResourceManager.GetString("S_ErrorSaveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error save quiz!.
        /// </summary>
        public static string S_ErrorSaveQuiz {
            get {
                return ResourceManager.GetString("S_ErrorSaveQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error save user info!.
        /// </summary>
        public static string S_ErrorSaveUser {
            get {
                return ResourceManager.GetString("S_ErrorSaveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error save variant!.
        /// </summary>
        public static string S_ErrorSaveVariants {
            get {
                return ResourceManager.GetString("S_ErrorSaveVariants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error view questions!.
        /// </summary>
        public static string S_ErrorViewQuestion {
            get {
                return ResourceManager.GetString("S_ErrorViewQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error view quiz!.
        /// </summary>
        public static string S_ErrorViewQuiz {
            get {
                return ResourceManager.GetString("S_ErrorViewQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error view variant!.
        /// </summary>
        public static string S_ErrorViewVariant {
            get {
                return ResourceManager.GetString("S_ErrorViewVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username or password.
        /// </summary>
        public static string S_IncorrectUsername {
            get {
                return ResourceManager.GetString("S_IncorrectUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid HTTP request!.
        /// </summary>
        public static string S_InvalidHTTP {
            get {
                return ResourceManager.GetString("S_InvalidHTTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid question request!.
        /// </summary>
        public static string S_InvalidQuestionRequest {
            get {
                return ResourceManager.GetString("S_InvalidQuestionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz is not valid!.
        /// </summary>
        public static string S_InvalidQuiz {
            get {
                return ResourceManager.GetString("S_InvalidQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid quiz request!.
        /// </summary>
        public static string S_InvalidQuizRequest {
            get {
                return ResourceManager.GetString("S_InvalidQuizRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user info!.
        /// </summary>
        public static string S_InvalidUserInfo {
            get {
                return ResourceManager.GetString("S_InvalidUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user info, error :.
        /// </summary>
        public static string S_InvalidUserInfoError {
            get {
                return ResourceManager.GetString("S_InvalidUserInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user request!.
        /// </summary>
        public static string S_InvalidUserRequest {
            get {
                return ResourceManager.GetString("S_InvalidUserRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid variant request!.
        /// </summary>
        public static string S_InvalidVariantRequest {
            get {
                return ResourceManager.GetString("S_InvalidVariantRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password validation failed, error :.
        /// </summary>
        public static string S_PasswordValidationError {
            get {
                return ResourceManager.GetString("S_PasswordValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz is not finished, question view is not allowed !.
        /// </summary>
        public static string S_QuizNotFinished {
            get {
                return ResourceManager.GetString("S_QuizNotFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz not found!.
        /// </summary>
        public static string S_QuizNotFound {
            get {
                return ResourceManager.GetString("S_QuizNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already exists!.
        /// </summary>
        public static string S_UsernameExists {
            get {
                return ResourceManager.GetString("S_UsernameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found!.
        /// </summary>
        public static string S_UserNotFound {
            get {
                return ResourceManager.GetString("S_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT User_ID,FirstName,LastName,UserName,HashedPassword,RolesFlag FROM QuizDB.dbo.V_M_USERS;.
        /// </summary>
        public static string SQLLoadPersons {
            get {
                return ResourceManager.GetString("SQLLoadPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
