CREATE VIEW [DBO].[V_M_QUIZES]
AS
	SELECT 
		[QUIZ_ID]
      ,[QUIZ_NAME]
      ,[AUTHOR_ID]
	  ,(SELECT ISNULL(FIRSTNAME,'') + ' ' + ISNULL(LASTNAME,'') FROM DBO.M_USERS WHERE M_USERS.USER_ID = M_QUIZES.AUTHOR_ID) as AUTHOR
      ,CONVERT(nvarchar(23),[CREATED_DATE],121) as [CREATED_DATE]
      ,[SUCCESS_RATE]
  FROM [DBO].[M_QUIZES]
