USE master;  
GO  
IF DB_ID (N'QuizDB') IS NULL
CREATE DATABASE QuizDB
GO  

USE [QuizDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


IF OBJECT_ID('dbo.M_QUIZ_ANSWERS', 'U') IS NOT NULL
	DROP TABLE [dbo].[M_QUIZ_ANSWERS]
GO

IF OBJECT_ID('dbo.M_QUIZ_RESULTS', 'U') IS NOT NULL
	DROP TABLE [dbo].[M_QUIZ_RESULTS]
GO

IF OBJECT_ID('dbo.M_VARIANTS', 'U') IS NOT NULL
	DROP TABLE [dbo].[M_VARIANTS]
GO

IF OBJECT_ID('dbo.M_QUESTIONS', 'U') IS NOT NULL
	DROP TABLE [dbo].[M_QUESTIONS]
GO

IF OBJECT_ID('dbo.M_QUIZES', 'U') IS NOT NULL
	DROP TABLE [dbo].[M_QUIZES]
GO

IF OBJECT_ID('dbo.M_COURSES', 'U') IS NOT NULL
	DROP TABLE [dbo].[M_COURSES]
GO

IF OBJECT_ID('dbo.M_USERS', 'U') IS NOT NULL
	DROP TABLE [dbo].[M_USERS]
GO

IF OBJECT_ID('dbo.T_LOG', 'U') IS NOT NULL
	DROP TABLE [dbo].T_LOG
GO

IF OBJECT_ID('dbo.S_PK_GENERATOR', 'U') IS NOT NULL
	DROP TABLE [dbo].[S_PK_GENERATOR]
GO

IF OBJECT_ID('dbo.V_M_USERS', 'V') IS NOT NULL
	DROP VIEW [dbo].[V_M_USERS]
GO



CREATE TABLE [dbo].[M_USERS](
	[USER_ID] [int] NOT NULL,
	[FIRSTNAME] [nvarchar](100) NOT NULL,
	[LASTNAME] [nvarchar](100) NOT NULL,
	[USERNAME] [nvarchar](100) NOT NULL,
	[HASHEDPASSWORD] [nvarchar](100) NOT NULL,
	[ROLESFLAG] [int] NOT NULL,
	[REGISTRATION_DATE] [datetime] NOT NULL,
	[LAST_LOGON_DATE] [datetime] NULL, 

    CONSTRAINT [PK_M_USERS] PRIMARY KEY CLUSTERED (	[USER_ID] ASC),
    CONSTRAINT [NK1_M_USERS] UNIQUE NONCLUSTERED (	[USERNAME] ASC)
) ON [PRIMARY]

GO

INSERT INTO [dbo].[M_USERS]
           ([USER_ID]
           ,[FIRSTNAME]
           ,[LASTNAME]
           ,[USERNAME]
           ,[HASHEDPASSWORD]
           ,[ROLESFLAG]
		   ,[REGISTRATION_DATE]
		   ,[LAST_LOGON_DATE])
     VALUES
           (1,'John','Doe', 'Jdoe', '123', 7, '1900-01-01',NULL),
		   (2,'Nikolay', 'Piskarev', 'np','123',3,'1900-01-01',NULL),
		   (3,'Igor','Kalugin','ki','123',7,'1900-01-01',NULL),
		   (4,'Barak','Obama','bo','123',1,'1900-01-01',NULL)
GO

CREATE TABLE [dbo].[S_PK_GENERATOR](
	[TABLE_NAME] [varchar](30) NOT NULL,
	[TABLE_ID] [numeric](18, 0) NOT NULL,

    CONSTRAINT [XPK_S_PK_GENERATOR] PRIMARY KEY CLUSTERED (	[TABLE_NAME] ASC)
) ON [PRIMARY]

GO

INSERT INTO [dbo].[S_PK_GENERATOR] ([TABLE_NAME],[TABLE_ID]) 
VALUES 
	('M_USERS',5),
	('M_QUIZES',1),
	('M_QUESTIONS',1),
	('M_VARIANTS',1),
	('M_COURSES',4)


/* ToDo : Переделать в соответсвии с гайдом */ 
CREATE TABLE [dbo].[T_LOG](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Date] [datetime] NOT NULL,
	[Thread] [varchar](255) NOT NULL,
	[Level] [varchar](50) NOT NULL,
	[Logger] [varchar](255) NOT NULL,
	[Message] [varchar](4000) NOT NULL,
	[Exception] [varchar](2000) NULL
) ON [PRIMARY]

GO


CREATE TABLE [dbo].[M_COURSES]
(
	[COURSE_ID] [int] NOT NULL,
	[COURSE_NAME] [nvarchar](100) NOT NULL,

    CONSTRAINT [PK_M_COURSES] PRIMARY KEY CLUSTERED (	[COURSE_ID] ASC),
	CONSTRAINT [NK1_M_COURSES] UNIQUE NONCLUSTERED (	[COURSE_NAME] ASC )
) 
GO
INSERT INTO  [dbo].[M_COURSES] ([COURSE_ID],[COURSE_NAME])
VALUES 
	(1,N'Английский язык'),
	(2,N'Русский язык'),
	(3,N'C# & Dot.NET')


CREATE TABLE [dbo].[M_QUIZES]
(
	[QUIZ_ID] [int] NOT NULL,
	[QUIZ_NAME] [nvarchar](100) NOT NULL,
	[COURSE_ID] [int] NOT NULL,
 	[AUTHOR_ID] [int] NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[SUCCESS_RATE] [real] NOT NULL

    CONSTRAINT [PK_M_QUIZES] PRIMARY KEY CLUSTERED (	[QUIZ_ID] ASC),
    CONSTRAINT [NK1_M_QUIZES] UNIQUE NONCLUSTERED (	[QUIZ_NAME] ASC ),
	CONSTRAINT [FK1_M_QUIZES] FOREIGN KEY ([AUTHOR_ID]) REFERENCES [dbo].[M_USERS] ([USER_ID]),
	CONSTRAINT [FK2_M_QUIZES] FOREIGN KEY ([COURSE_ID]) REFERENCES [dbo].[M_COURSES] ([COURSE_ID]) ON DELETE CASCADE,
	CONSTRAINT [CK1_M_QUIZES] CHECK ([SUCCESS_RATE] >0 AND [SUCCESS_RATE] <= 1 )
) 
GO

CREATE TABLE [dbo].[M_QUESTIONS]
(
	[QUESTION_ID] [int] NOT NULL,
	[QUIZ_ID] [int] NOT NULL,
	[INFO] [nvarchar](1000) NOT NULL,
	[TEXT] [nvarchar](1000) NOT NULL,
 	[CORRECT_OPTION_FLAG] [int] NOT NULL

    CONSTRAINT [PK_M_QUESTIONS] PRIMARY KEY CLUSTERED (	[QUESTION_ID] ASC),
	CONSTRAINT [FK1_M_QUESTIONS] FOREIGN KEY ([QUIZ_ID]) REFERENCES [dbo].[M_QUIZES] ([QUIZ_ID]),
) 
GO


CREATE TABLE [dbo].[M_VARIANTS]
(
	[VARIANT_ID] [int] NOT NULL,
	[QUESTION_ID] [int] NOT NULL,
	[VALUE] [int] NOT NULL,
	[TEXT] [nvarchar](1000) NOT NULL

    CONSTRAINT [PK_M_VARIANTS] PRIMARY KEY CLUSTERED (	[VARIANT_ID] ASC),
	CONSTRAINT [FK1_M_VARIANTS] FOREIGN KEY ([QUESTION_ID]) REFERENCES [dbo].[M_QUESTIONS] ([QUESTION_ID]),
) 
GO


CREATE TABLE [dbo].[M_QUIZ_RESULTS]
(
	[QUIZ_RESULTS_ID] [int] NOT NULL,
	[USER_ID] [int] NOT NULL,
	[QUIZ_ID] [int] NOT NULL,
	[QUIZ_STATUS] [int] NOT NULL,
	[ASSIGNED_BY_ID] [int] NOT NULL,
	[ASSIGNED_DATE] [datetime] NOT NULL,
	[COMPLETED_RATE] [real] NULL,
	[COMPLETED_DATE] [datetime] NULL

    CONSTRAINT [PK_M_QUIZ_RESULTS] PRIMARY KEY CLUSTERED (	[QUIZ_RESULTS_ID] ASC),
	CONSTRAINT [FK1_M_QUIZ_RESULTS] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[M_USERS] ([USER_ID]),
	CONSTRAINT [FK2_M_QUIZ_RESULTS] FOREIGN KEY ([QUIZ_ID]) REFERENCES [dbo].[M_QUIZES] ([QUIZ_ID]),
	CONSTRAINT [FK3_M_QUIZ_RESULTS] FOREIGN KEY ([ASSIGNED_BY_ID]) REFERENCES [dbo].[M_USERS] ([USER_ID]),
	CONSTRAINT [CK1_M_QUIZ_RESULTS] CHECK ([COMPLETED_DATE] >0 AND [COMPLETED_DATE] <= 1 )
) 
GO

CREATE TABLE [dbo].[M_QUIZ_ANSWERS]
(
	[QUIZ_ANSWERS_ID] [int] NOT NULL,
	[QUIZ_ID] [int] NOT NULL,
	[QUESTION_ID] [int] NOT NULL,
	[ANSWER_FLAG] [int] NOT NULL,
	[ANSWER_DATE] [datetime] NOT NULL,
	[ELAPSED_TIME] [int] NOT NULL

    CONSTRAINT [PK_M_QUIZ_ANSWERS] PRIMARY KEY CLUSTERED (	[QUIZ_ANSWERS_ID] ASC),
	CONSTRAINT [FK1_M_QUIZ_ANSWERS] FOREIGN KEY ([QUIZ_ID]) REFERENCES [dbo].[M_QUIZES] ([QUIZ_ID]),
	CONSTRAINT [FK2_M_QUIZ_ANSWERS] FOREIGN KEY ([QUESTION_ID]) REFERENCES [dbo].[M_QUESTIONS] ([QUESTION_ID]),
) 
GO



CREATE VIEW [dbo].[V_M_USERS]
AS
SELECT [USER_ID], [FIRSTNAME], [LASTNAME], [USERNAME], [HASHEDPASSWORD], [ROLESFLAG], [REGISTRATION_DATE], [LAST_LOGON_DATE]
FROM  dbo.M_USERS

