CREATE PROCEDURE [dbo].[P_DELETEUSER]
	@USERID int = 0,
	@ERROR int out,
	@ERRORTEXT nvarchar(100) out

AS
BEGIN
	SET @ERROR = 0;
	SET @ERRORTEXT = N'Delete Ok';
	BEGIN TRY
		IF EXISTS(SELECT * FROM dbo.M_USERS WHERE USER_ID = @USERID)
			DELETE FROM dbo.M_USERS WHERE USER_ID = @USERID
		ELSE
			SELECT @ERROR = -1,	@ERRORTEXT = N'No UserID '+CAST(@USERID as nvarchar(10)) + N' in M_USERS table';
	END TRY
	BEGIN CATCH
		SELECT @ERROR = ERROR_NUMBER(), @ERRORTEXT = ERROR_MESSAGE();
	END CATCH
	RETURN 0
END