CREATE PROCEDURE [DBO].[P_STATSBYUSERQUIZ]
@USER_ID INT,
@QUIZ_ID int 
AS
BEGIN

	DECLARE @Quiz_Status int = ISNULL((SELECT QUIZ_STATUS FROM [DBO].[M_QUIZ_RESULTS] WHERE QUIZ_ID = @QUIZ_ID AND USER_ID= @USER_ID),0)
	SELECT 
		Q.[INFO], 
		Q.[TEXT],
		CASE WHEN 
				(SELECT QA.ANSWER_FLAG
			FROM DBO.M_QUIZ_RESULTS QR
			JOIN DBO.M_QUIZ_ANSWERS QA ON QA.QUIZ_RESULT_ID = QR.QUIZ_RESULT_ID
			WHERE QR.USER_ID = @USER_ID
			AND QR.QUIZ_ID = Q.QUIZ_ID
			AND QA.QUESTION_ID = Q.QUESTION_ID) IS NULL
			THEN 'NOT ANSWERED'
		WHEN Q.CORRECT_OPTION_FLAG =
		(
			SELECT QA.ANSWER_FLAG
			FROM DBO.M_QUIZ_RESULTS QR
			JOIN DBO.M_QUIZ_ANSWERS QA ON QA.QUIZ_RESULT_ID = QR.QUIZ_RESULT_ID
			WHERE QR.USER_ID = @USER_ID
			AND QR.QUIZ_ID = Q.QUIZ_ID
			AND QA.QUESTION_ID = Q.QUESTION_ID
		)
		THEN 'RIGHT' 
		ELSE 'WRONG' END
			AS RESULT
	 FROM M_QUESTIONS Q
	WHERE Q.QUIZ_ID = @QUIZ_ID
	ORDER BY Q.QUESTION_ID
END