CREATE TABLE [dbo].[M_VARIANTS]
(
	[VARIANT_ID] [int] NOT NULL,
	[QUESTION_ID] [int] NOT NULL,
	[VALUE] [int] NOT NULL,
	[TEXT] [nvarchar](1000) NOT NULL

    CONSTRAINT [PK_M_VARIANTS] PRIMARY KEY CLUSTERED (	[VARIANT_ID] ASC),
	CONSTRAINT [FK1_M_VARIANTS] FOREIGN KEY ([QUESTION_ID]) REFERENCES [dbo].[M_QUESTIONS] ([QUESTION_ID]) ON DELETE CASCADE,
) 
